### ISSUE TITLE
[somtimes]Not working

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [HessiJames/kde-color-folder#3]
My dolphin is 17.12.2 and I found that they are using different metadata format from the script here is using.

From the folder I manually changed icon from "Properties",
`[Desktop Entry]
Icon=folder-orange

[Dolphin]
HeaderColumnWidths=386,76,138
Icon=folder-green
Timestamp=2018,3,11,15,15,36
Version=4

[Settings]
HiddenFilesShown=true`

The Icon attribute is stored in "Desktop Entry" instead of "Dolphin", while the script is doing the later, which is not working

Thanks for the script anyways.

**Comment by dfaust** [comment]
Thank you for your report. But could you please double check that behavior and the `Color Folder` version. The current version (2.0.2) does use the "Desktop Entry" group.

**Comment by rtsui-harmonicinc** [comment]
Yes, it's the latest version
I tried for a few times, it sometimes put in Dolphin, sometimes put in Desktop Entry.

For example, in Music folder, the first time I get this, there was no existing .directory

> [Dolphin]
> Icon=folder-red
> PreviewsShown=true
> Timestamp=2018,3,16,22,40,45
> Version=4
> 
> [Settings]
> HiddenFilesShown=true

While the second time I get this, after deleting existing .directory.

> [Desktop Entry]
> Icon=folder-red
> 
> [Dolphin]
> PreviewsShown=true
> Timestamp=2018,3,16,22,41,36
> Version=4
> 
> [Settings]
> HiddenFilesShown=true
> 

Really strange, it seems.

**Comment by dfaust** [comment]
Alright, thanks again for the report, it was indeed a bug. You can check out the new version, it should fix the issue. And I'll release a new version in the coming days.
